# Content-based filtering

---

Xây dựng model Content-based filtering:
- Gensim
- Cosine_similarity

Thực hiện đánh giá kết quả
- Kết luận

## COMMENTS: 
We will test the recommendation system based on what has been analyzed in the previous steps.
Which clustering users into three groups:
- Those who are interested in beginner courses
- Those who are interested in professional certificates
- Those who are interested in advanced courses.

In [1]:
from modules.data_preprocessing import DataPreprocessing
from modules.models import ProcessModels
from modules.recommendation import Recommendation

### Gensim - Content-based filtering

---

In [2]:
recommendation = Recommendation(
    process_model_module=ProcessModels(DataPreprocessing(), spark=None, model_dir='models/'),
)

In [3]:
recommendations = recommendation.gensim_recommender(
    user_search='Beginner friendly courses',
    num_recommendations=10,
)
recommendations

,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,SimilarityScore
542,"Data – What It Is, What We Can Do With It",151,4.6,Beginner level,Johns Hopkins University,NaN,0.214090
262,Linear Regression and Modeling,1686,4.8,Beginner level,Duke University,NaN,0.144611
264,Inferential Statistics,2624,4.8,Beginner level,Duke University,NaN,0.137208
81,Fundamentals of Scalable Data Science,2051,4.3,Beginner level,IBM,NaN,0.134539
181,AI and Public Health,151,4.7,Beginner level,DeepLearning.AI,NaN,0.132910
328,Python Data Analytics,23,4.3,Beginner level,Meta,NaN,0.131331
171,Business Statistics and Analysis Specialization,7318,4.7,Beginner level,Rice University,NaN,0.130208
812,Data Literacy Specialization,155,4.6,Beginner level,Johns Hopkins University,NaN,0.129702
190,Introduction to Probability and Data with R,5569,4.7,Beginner level,Duke University,NaN,0.127869
61,Data Visualization with Advanced Excel,2925,4.8,Beginner level,PwC,NaN,0.123161

## COMMENTS:
- The model recommends courses that are suitable for beginners.
- All the courses are beginner-friendly and are from different providers.
- The model can recommend courses based on the user’s search and is consistent with the user’s search. Consider applying successful.

In [4]:
recommendations = recommendation.gensim_recommender(
    user_search='Amazon AWS',
    num_recommendations=10,
)
recommendations

,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,SimilarityScore
760,AWS: Data Analysis and Visualization,0,0.0,Beginner level,Whizlabs,Understand analysis and visualization based se...,0.329609
521,Building Recommendation System Using MXNET on ...,0,0.0,Advanced level,Coursera Project Network,Learn how to train a Recommendation System usi...,0.321563
267,Exam Prep DAS-C01: AWS Certified Data Analytic...,9,4.6,Beginner level,Whizlabs,Gain Skills to understand the fundamentals of ...,0.297471
735,Exploratory Data Analysis in AWS,0,0.0,Beginner level,Whizlabs,Analyze and visualize data for machine learni...,0.284014
375,MLOps Platforms: Amazon SageMaker and Azure ML,27,3.8,Advanced level,Duke University,Apply exploratory data analysis (EDA) techniqu...,0.282503
251,Introduction to Designing Data Lakes on AWS,220,4.7,Intermediate level,Amazon Web Services,Where to start with a Data Lake?\nHow to build...,0.237941
737,Modeling in AWS,0,0.0,Beginner level,Whizlabs,Analyze Modeling Concepts and train Machine Le...,0.190547
530,AWS: Data Collection Systems,0,0.0,Beginner level,Whizlabs,Describe data collection stages and compare th...,0.185255
33,MLOps | Machine Learning Operations Specializa...,120,3.9,Advanced level,Duke University,"Master Python fundamentals, MLOps principles, ...",0.178645
723,Image Classification with Amazon Sagemaker,98,4.6,Advanced level,Coursera Project Network,Prepare data for Sagemaker Image Classificatio...,0.155659

## COMMENTS:
- The model recommends courses related to Amazon AWS.
- All the courses are related to Amazon AWS but there's inconsistency with the average rating. Some courses have a high rating while others have a low rating.
- The model can recommend courses based on the user’s search but there's inconsistency with the average rating. Consider applying successful as content-based filtering is based on the user’s search, not the average rating.

In [5]:
recommendations = recommendation.gensim_recommender(
    user_search='Data courses from IBM',
    num_recommendations=10,
)
recommendations

,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,SimilarityScore
58,Advanced Data Science with IBM Specialization,2391,4.4,Advanced level,IBM,NaN,0.692102
108,IBM AI Foundations for Business Specialization,1279,4.7,Beginner level,IBM,NaN,0.638204
154,IBM AI Enterprise Workflow Specialization,186,4.4,Advanced level,IBM,NaN,0.540988
59,Exploratory Data Analysis for Machine Learning,1629,4.6,Intermediate level,IBM,NaN,0.501292
273,Unsupervised Machine Learning,231,4.7,Intermediate level,IBM,NaN,0.463438
206,Supervised Machine Learning: Regression,518,4.7,Intermediate level,IBM,NaN,0.420808
228,Supervised Machine Learning: Classification,311,4.8,Intermediate level,IBM,NaN,0.417058
630,Advanced Data Science Capstone,388,4.6,Advanced level,IBM,NaN,0.388035
81,Fundamentals of Scalable Data Science,2051,4.3,Beginner level,IBM,NaN,0.375511
259,Deep Learning and Reinforcement Learning,180,4.6,Intermediate level,IBM,NaN,0.373437

## COMMENTS:
- The model recommends courses related to IBM.
- All the courses are related to IBM. Consider applying successful.

In [6]:
recommendations = recommendation.gensim_recommender(
    user_search='ML Pipelines on Google Cloud',
    num_recommendations=10,
)
recommendations

,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,SimilarityScore
460,ML Pipelines on Google Cloud,74,3.4,Advanced level,Google Cloud,NaN,0.919051
37,Advanced Machine Learning on Google Cloud Spec...,1925,4.5,Advanced level,Google Cloud,NaN,0.507103
432,Natural Language Processing on Google Cloud,516,4.4,Advanced level,Google Cloud,NaN,0.469875
570,Serverless Data Processing with Dataflow: Deve...,38,4.1,Advanced level,Google Cloud,NaN,0.435830
203,Google Cloud Big Data and Machine Learning Fun...,15932,4.7,Beginner level,Google Cloud,Identify the data-to-AI lifecycle on Google Cl...,0.429437
240,Machine Learning with Apache Spark,55,4.6,Intermediate level,IBM,"Describe ML, explain its role in data engineer...",0.428470
105,Hands-on Foundations for Data Science and Mach...,93,4.2,Intermediate level,Google Cloud,NaN,0.426423
132,Preparing for Google Cloud Certification: Clou...,6898,4.6,Intermediate level,Google Cloud,Identify the purpose and value of the key Big ...,0.418224
38,Machine Learning on Google Cloud Specialization,8457,4.6,Intermediate level,Google Cloud,"Use Vertex AI AutoML and BigQuery ML to build,...",0.396745
485,Managing Machine Learning Projects with Google...,3605,4.6,Beginner level,Google Cloud,Explore common machine learning use cases impl...,0.376991

## COMMENTS:
- We search for specific courses related to ML Pipelines on Google Cloud.
- The model recommends courses related to ML Pipelines on Google Cloud. Consider applying successful.

### Cosine_similarity

---

In [7]:
recommendations = recommendation.cosine_similarity_recommender(
    user_search='Beginner',
    num_recommendations=10,
)
recommendations

,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,SimilarityScore
328,Python Data Analytics,23,4.3,Beginner level,Meta,NaN,0.224984
264,Inferential Statistics,2624,4.8,Beginner level,Duke University,NaN,0.221158
262,Linear Regression and Modeling,1686,4.8,Beginner level,Duke University,NaN,0.218998
81,Fundamentals of Scalable Data Science,2051,4.3,Beginner level,IBM,NaN,0.210440
812,Data Literacy Specialization,155,4.6,Beginner level,Johns Hopkins University,NaN,0.206390
190,Introduction to Probability and Data with R,5569,4.7,Beginner level,Duke University,NaN,0.206222
223,Basic Statistics,4369,4.6,Beginner level,University of Amsterdam,NaN,0.204744
171,Business Statistics and Analysis Specialization,7318,4.7,Beginner level,Rice University,NaN,0.202566
796,Data Literacy in Practice,0,0.0,Beginner level,SAS,NaN,0.201722
61,Data Visualization with Advanced Excel,2925,4.8,Beginner level,PwC,NaN,0.198674

## COMMENTS:
- The model recommends courses that are suitable for beginners.
- All the courses are beginner-friendly and are from different providers.
- The model can recommend courses based on the user’s search and is consistent with the user’s search. Consider applying successful.

In [8]:
recommendations = recommendation.cosine_similarity_recommender(
    user_search='ML Pipelines on Google Cloud',
    num_recommendations=10,
)
recommendations

,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,SimilarityScore
460,ML Pipelines on Google Cloud,74,3.4,Advanced level,Google Cloud,NaN,0.912421
37,Advanced Machine Learning on Google Cloud Spec...,1925,4.5,Advanced level,Google Cloud,NaN,0.547534
432,Natural Language Processing on Google Cloud,516,4.4,Advanced level,Google Cloud,NaN,0.535601
105,Hands-on Foundations for Data Science and Mach...,93,4.2,Intermediate level,Google Cloud,NaN,0.452813
570,Serverless Data Processing with Dataflow: Deve...,38,4.1,Advanced level,Google Cloud,NaN,0.426559
132,Preparing for Google Cloud Certification: Clou...,6898,4.6,Intermediate level,Google Cloud,Identify the purpose and value of the key Big ...,0.423778
203,Google Cloud Big Data and Machine Learning Fun...,15932,4.7,Beginner level,Google Cloud,Identify the data-to-AI lifecycle on Google Cl...,0.399767
38,Machine Learning on Google Cloud Specialization,8457,4.6,Intermediate level,Google Cloud,"Use Vertex AI AutoML and BigQuery ML to build,...",0.396642
240,Machine Learning with Apache Spark,55,4.6,Intermediate level,IBM,"Describe ML, explain its role in data engineer...",0.387695
331,How Google does Machine Learning,7218,4.6,Beginner level,Google Cloud,Describe Vertex AI Platform and how it's used ...,0.376194

## COMMENTS:
- We search for specific courses related to ML Pipelines on Google Cloud.
- The model recommends courses related to ML Pipelines on Google Cloud. Consider applying successful.

In [9]:
recommendations = recommendation.cosine_similarity_recommender(
    user_search='Data courses from IBM',
    num_recommendations=10,
)
recommendations

,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,SimilarityScore
58,Advanced Data Science with IBM Specialization,2391,4.4,Advanced level,IBM,NaN,0.488194
108,IBM AI Foundations for Business Specialization,1279,4.7,Beginner level,IBM,NaN,0.448203
154,IBM AI Enterprise Workflow Specialization,186,4.4,Advanced level,IBM,NaN,0.409235
59,Exploratory Data Analysis for Machine Learning,1629,4.6,Intermediate level,IBM,NaN,0.361950
273,Unsupervised Machine Learning,231,4.7,Intermediate level,IBM,NaN,0.323065
81,Fundamentals of Scalable Data Science,2051,4.3,Beginner level,IBM,NaN,0.311232
630,Advanced Data Science Capstone,388,4.6,Advanced level,IBM,NaN,0.304807
206,Supervised Machine Learning: Regression,518,4.7,Intermediate level,IBM,NaN,0.293161
228,Supervised Machine Learning: Classification,311,4.8,Intermediate level,IBM,NaN,0.291345
563,Scripting with Python and SQL for Data Enginee...,76,4.4,Intermediate level,Duke University,Extract data from different sources and map it...,0.283105

## COMMENTS:
- The model recommends courses related to IBM.
- All the courses are related to IBM. Consider applying successful.
- Most of the courses recommended are related to IBM, however these courses have null values in results, perhaps due to the lack of information from the provider.

In [10]:
recommendations = recommendation.cosine_similarity_recommender(
    user_search='Amazon AWS',
    num_recommendations=10,
)
recommendations

,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,SimilarityScore
760,AWS: Data Analysis and Visualization,0,0.0,Beginner level,Whizlabs,Understand analysis and visualization based se...,0.325632
521,Building Recommendation System Using MXNET on ...,0,0.0,Advanced level,Coursera Project Network,Learn how to train a Recommendation System usi...,0.314102
735,Exploratory Data Analysis in AWS,0,0.0,Beginner level,Whizlabs,Analyze and visualize data for machine learni...,0.283117
267,Exam Prep DAS-C01: AWS Certified Data Analytic...,9,4.6,Beginner level,Whizlabs,Gain Skills to understand the fundamentals of ...,0.268899
375,MLOps Platforms: Amazon SageMaker and Azure ML,27,3.8,Advanced level,Duke University,Apply exploratory data analysis (EDA) techniqu...,0.256103
251,Introduction to Designing Data Lakes on AWS,220,4.7,Intermediate level,Amazon Web Services,Where to start with a Data Lake?\nHow to build...,0.212204
530,AWS: Data Collection Systems,0,0.0,Beginner level,Whizlabs,Describe data collection stages and compare th...,0.179606
737,Modeling in AWS,0,0.0,Beginner level,Whizlabs,Analyze Modeling Concepts and train Machine Le...,0.171749
33,MLOps | Machine Learning Operations Specializa...,120,3.9,Advanced level,Duke University,"Master Python fundamentals, MLOps principles, ...",0.163761
723,Image Classification with Amazon Sagemaker,98,4.6,Advanced level,Coursera Project Network,Prepare data for Sagemaker Image Classificatio...,0.145882

## COMMENTS:
- The model recommends courses related to Amazon AWS.
- All the courses are related to Amazon AWS but there's inconsistency with the average rating. Some courses have a high rating while others have a low rating.
- The model can recommend courses based on the user’s search but there's inconsistency with the average rating. Consider applying successful as content-based filtering is based on the user’s search, not the average rating.

In [11]:
recommendations = recommendation.cosine_similarity_recommender(
    user_search='Linear Algebra',
    num_recommendations=10,
)
recommendations

,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,SimilarityScore
424,"Linear Algebra: Matrix Algebra, Determinants, ...",19,4.8,NaN,Johns Hopkins University,NaN,0.679030
323,Linear Algebra: Linear Systems and Matrix Equa...,31,4.7,Beginner level,Johns Hopkins University,NaN,0.622104
29,Linear Algebra from Elementary to Advanced Spe...,39,4.8,Beginner level,Johns Hopkins University,NaN,0.548256
562,Linear Algebra: Orthogonality and Diagonalization,11,4.9,Intermediate level,Johns Hopkins University,NaN,0.520875
162,Mathematics for Machine Learning: Linear Algebra,11947,4.7,Beginner level,Imperial College London,NaN,0.502137
92,Advanced Linear Models for Data Science 2: Sta...,93,4.5,Advanced level,Johns Hopkins University,NaN,0.317830
592,Linear Regression and Multiple Linear Regressi...,17,4.1,Beginner level,Coursera Project Network,Learn about linear regression and multiple lin...,0.304590
466,Linear Regression with Python,421,4.6,Intermediate level,Coursera Project Network,"Create a linear model, and implement gradient ...",0.262938
262,Linear Regression and Modeling,1686,4.8,Beginner level,Duke University,NaN,0.257447
664,Simple Linear Regression for the Absolute Begi...,21,4.7,Beginner level,Coursera Project Network,Understand the theory and intuition behind sim...,0.233009

## COMMENTS:
- The model recommends courses related to Linear Algebra.
- All the courses are related to Linear Algebra. Consider applying successful.

### Content-based filtering conclusion

---
For this demonstration, Users can search for courses using keywords.
The model was trained on a dataset using all information available in the dataset,
such as courses’ names, descriptions and providers, levels.


Both method Gensim and Cosine_similarity are consistent in recommending the same courses for the same user search.
The model can be used to recommend courses to users based on their search.
This is because both Gensim and cosine similarity approaches use TF-IDF (Term Frequency-Inverse Document Frequency) for representing the text data.

- Gensim TF-IDF: Gensim's TF-IDF model transforms the corpus (a collection of tokenized documents) into TF-IDF vectors.
Gensim then uses these TF-IDF vectors to compute the similarity between documents and the query.


- Scikit-learn Cosine Similarity with TF-IDF: Scikit-learn's TfidfVectorizer directly transforms the text data into TF-IDF vectors. Cosine similarity is then computed directly using these TF-IDF vectors to find the similarity between documents and the query.

# Collaborative Filtering

---
Xây dựng model Collaborative Filtering
- pyspark.ml.recommendation.ALS
- Surprise

Thực hiện đánh giá kết quả
- RMSE
- Kết luận

In [12]:
# Get all unique ReviewerIDs and corresponding ReviewerNames
user_ids = DataPreprocessing().get_all_user_ids()

In [13]:
user_ids

            ReviewerName                        ReviewerID
0             By Kevin M  dcd5115659af4c21aafdd91063bd994b
1           By Jianfei Z  ef31c37f264c42ca8bd487105725aa69
2              By Aman J  1ff27276ebd145958312a25947514150
3             By pooja s  13d4a80599cf4c4f8f4c3b511e25a4d9
4            By Lauren J  2dc81e9b8813477f9b3fc97c08456157
...                  ...                               ...
223519   By Shashank N S  a7aa9c9ec724410a8ba0b9aca7e6787c
223525         By Mars G  6113792be4f14108871e0486764f8db1
223526   By kulbhushan s  cd702e2c27cf47febf5960263cfa423c
223533  By Charles W C I  6d8210f1f5c24870bc88fa0e178d242d
223538       By Moaish P  88b40679895a4119b5f5a5e29e1a85b3

[119259 rows x 2 columns]

## COMMENTS:
- We will use UUID (Universally Unique Identifier) to identify users.
- UUID is a 128-bit number used to uniquely identify information. It is a 32-character hexadecimal string. The UUID is unique and can be used to identify users. Its uniqueness is guaranteed by the algorithm used to generate it. The purpose of using UUID is to ensure that on a large scale, the probability of two users having the same UUID is considered negligible. This is important for the recommendation system as it ensures that the system is to consistently and discreetly identify users.

In [14]:
recommendations, user_history = recommendation.surprise_recommender(
    current_user_id='03223df4cd824c43b765115fa2b822e7', # By Mark L
    num_recommendations=10,
)

## COMMENTS:
- For the Surprise SVD algorithm, an RMSE below 1.0 is often considered good,
and an RMSE below 0.9 is considered excellent.
- In this case, RMSE between 0.8 and 0.9 would mean a strong model performance.
Values closer to 0.8 suggest the model is good at predicting user ratings.
- The RMSE values across the 5 folds are consistently below 0.9, with an average of 0.8911 and a standard deviation of 0.0039. This indicates that the SVD model is performing well, with low variability across different data splits.
- Fit time: The model fitting times are fairly consistent, averaging around 1.35 seconds per fold, indicating a stable training process.
- Test time: The test times vary slightly more but remain low, averaging around 0.14 seconds, which is efficient for practical use.

In [15]:
recommendations

,CourseID,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,EstimatedRating
0,11d4aeafdfb44ae197e30df18b37fdbd,"Foundations: Data, Data, Everywhere",99239,4.8,Beginner level,Google,Define and explain key concepts involved in da...,5
1,66b9626c9fdc4e9092b681a918c52247,Generative AI: Elevate Your Data Science Career,20,4.8,Intermediate level,IBM,"Leverage generative AI tools, like GPT 3.5, C...",5
2,fe5dddb726d741b7af972c875462ff82,Data Science Project: MATLAB for the Real World,24,4.8,Intermediate level,MathWorks,"Apply a full data science workflow, including ...",5
3,409f8d989f9741e496c1136833c1227a,Neural Networks and Deep Learning,120907,4.9,Intermediate level,DeepLearning.AI,NaN,5
4,48632036d36a4f52afcbe9cacec6bf62,"Unsupervised Learning, Recommenders, Reinforce...",2597,4.9,Beginner level,DeepLearning.AI,Use unsupervised learning techniques for unsup...,5
5,d9a7417d1ea640dfa6b8d5ead6848f0d,Introduction to Machine Learning in Production,2818,4.8,Advanced level,DeepLearning.AI,Identify the key components of the ML lifecycl...,5
6,90ceb70be576477f9ea7e14f89f945cc,Data Visualization and Dashboards with Excel a...,3428,4.7,Beginner level,IBM,Create basic visualizations such as line graph...,5
7,f83a0b870c3c457dab31f72138574c2b,AI and Public Health,151,4.7,Beginner level,DeepLearning.AI,NaN,5
8,a6732c6430f84e5b92e6fe0d03774539,Applied Data Science Capstone,6993,4.7,Intermediate level,IBM,Demonstrate proficiency in data science and ma...,5
9,5297b5a5e192448aa1c340619a9abcb7,Managing Machine Learning Projects,135,4.8,Beginner level,Duke University,NaN,5

In [16]:
user_history

,CourseID,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,RatingStar
0,b6247bd0233443ba80cd67788ead9baa,What is Data Science?,68152,4.7,Beginner level,IBM,Define data science and its importance in toda...,1
1,b6247bd0233443ba80cd67788ead9baa,What is Data Science?,68152,4.7,Beginner level,IBM,Define data science and its importance in toda...,5
2,bc505373fadb40b1bb0f872dbf3a99c6,Generative AI: Prompt Engineering Basics,238,4.8,Beginner level,IBM,Explain the concept and relevance of prompt en...,5
3,7cf2cfbb07cb4aa6ac720b9578000521,Data Visualization with Advanced Excel,2925,4.8,Beginner level,PwC,NaN,5
4,241e0dd38635483f8a9d5e99fcfe8f23,Advanced Linear Models for Data Science 2: Sta...,93,4.5,Advanced level,Johns Hopkins University,NaN,5
5,711d7f48e45741c692555bf2490ca205,Data Science Methodology,19946,4.6,Beginner level,IBM,Describe what a data science methodology is an...,5
6,409f8d989f9741e496c1136833c1227a,Neural Networks and Deep Learning,120907,4.9,Intermediate level,DeepLearning.AI,NaN,5
7,093ee4830c8244ffa6d896fcf240a032,Prepare Data for Exploration,19054,4.8,Beginner level,Google,Explain what factors to consider when making d...,5
8,f0e79a0fdfe345c3844a04dd7339cd53,Improving Deep Neural Networks: Hyperparameter...,62856,4.9,Intermediate level,DeepLearning.AI,NaN,5
9,f0e79a0fdfe345c3844a04dd7339cd53,Improving Deep Neural Networks: Hyperparameter...,62856,4.9,Intermediate level,DeepLearning.AI,NaN,3
10,65337d37ece541429d711c610ba1176d,Machine Learning with Python,15351,4.7,Intermediate level,IBM,Describe the various types of Machine Learning...,5
11,50e2a0ddfb1f4892ad5d4f66e80aba51,Convolutional Neural Networks,42059,4.9,Intermediate level,DeepLearning.AI,NaN,5
12,3a3e9436bd8045d3812e868b960a4045,Sequence Models,29881,4.8,Intermediate level,DeepLearning.AI,NaN,5
13,3a3e9436bd8045d3812e868b960a4045,Sequence Models,29881,4.8,Intermediate level,DeepLearning.AI,NaN,5
14,1ea0ef9d9ff3446c9f41eabb9260d46d,Natural Language Processing with Classificatio...,4274,4.6,Intermediate level,DeepLearning.AI,"Use logistic regression, naïve Bayes, and word...",3
15,6205af98a49f4fab994f263f933f4bf2,Data Visualization with Python,11517,4.5,Intermediate level,IBM,Implement data visualization techniques and pl...,5
16,6205af98a49f4fab994f263f933f4bf2,Data Visualization with Python,0,0.0,Intermediate level,Duke University,"Apply Python, spreadsheets, and BI tooling pro...",5
17,4955ffa3878d49ff9d94aee5200ab083,Introduction to Data Science in Python,26908,4.5,Intermediate level,University of Michigan,Understand techniques such as lambdas and mani...,5
18,a3e4dd734bfc4fcebd7b77800ee40313,Natural Language Processing with Attention Models,972,4.4,Intermediate level,DeepLearning.AI,"Use encoder-decoder, causal, & self-attention ...",3
19,af853697798047458d17cadea9e5fff9,Build Better Generative Adversarial Networks (...,636,4.7,Intermediate level,DeepLearning.AI,NaN,4
20,4078a74ebebc466cb3edf068d8e3e4ba,Problem Solving with Excel,5264,4.7,Beginner level,PwC,NaN,5
21,fd0e6281739c41fe91cb5a171600cb4a,Sample-based Learning Methods,1216,4.8,Intermediate level,University of Alberta,NaN,3
22,06c9a7cfb1464b3c9688cb0a0637683f,Apply Generative Adversarial Networks (GANs),507,4.8,Intermediate level,DeepLearning.AI,NaN,5
23,dbe8ae364c124db787028d8e2a12355a,AI For Medical Treatment,505,4.7,Intermediate level,DeepLearning.AI,Estimate treatment effects using data from ran...,3
24,0209f65d0580463c9a018c98603b2350,How Google does Machine Learning,7218,4.6,Beginner level,Google Cloud,Describe Vertex AI Platform and how it's used ...,5

## COMMENTS:
- About this user, Mark: He's interested in beginner courses, Deep Learning, Machine learning and AI for medical care or Excel.
- The model is consistent with the user's history as suggested courses are related, such as Fundamentals of Machine Learning for Healthcare, Ethical Issues in Data Science, Data Analysis and Visualization with Power BI, and more.

In [17]:
recommendations, user_history = recommendation.surprise_recommender(
    current_user_id='13d4a80599cf4c4f8f4c3b511e25a4d9', # By pooja s
    num_recommendations=10,
)

In [18]:
recommendations

,CourseID,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,EstimatedRating
0,409f8d989f9741e496c1136833c1227a,Neural Networks and Deep Learning,120907,4.9,Intermediate level,DeepLearning.AI,NaN,4.995421
1,11d4aeafdfb44ae197e30df18b37fdbd,"Foundations: Data, Data, Everywhere",99239,4.8,Beginner level,Google,Define and explain key concepts involved in da...,4.984688
2,019208b36534424daad46ca178108182,"The Power of Machine Learning: Boost Business,...",145,4.8,Beginner level,SAS,Participate in the deployment of machine learn...,4.964113
3,9a86f8d7de174898acf3c35600040106,Introduction to Node-red,37,4.8,Beginner level,Coursera Project Network,Learn to work with Node-Red Environment\nLearn...,4.923475
4,1012a6fa755745488d530e6b632589ae,Structured Query Language (SQL) using SAS,252,4.9,NaN,SAS,NaN,4.901048
5,f83a0b870c3c457dab31f72138574c2b,AI and Public Health,151,4.7,Beginner level,DeepLearning.AI,NaN,4.899728
6,aa8ddd96f08b456c9b3d1532195091ce,"Big Data, Artificial Intelligence, and Ethics",477,4.6,Beginner level,"University of California, Davis",Define and discuss big data opportunities and ...,4.888741
7,baeaa433af3b492db14e8c6423fc76fe,Exploratory Data Analysis with MATLAB,795,4.8,Beginner level,MathWorks,Import large tabular datasets & customize the ...,4.876848
8,23df2c5d25944451a049a2cb6b9e1e98,Computer Simulations,79,4.5,Beginner level,"University of California, Davis",NaN,4.866206
9,9d0057791a4f4cc984cc90f9b5b7f407,Linear Algebra: Orthogonality and Diagonalization,11,4.9,Intermediate level,Johns Hopkins University,NaN,4.865472

In [19]:
user_history

,CourseID,CourseName,ReviewNumber,AvgStar,Level,Unit,Results,RatingStar
0,b6247bd0233443ba80cd67788ead9baa,What is Data Science?,68152,4.7,Beginner level,IBM,Define data science and its importance in toda...,1
1,87900c57bcb44e9b9c4c04015153ddc1,"Python for Data Science, AI & Development",35369,4.6,Beginner level,IBM,Learn Python - the most popular programming la...,4
2,c9c2325cd8c5414392bfe9586bc7fce1,Basic Statistics,4369,4.6,Beginner level,University of Amsterdam,NaN,5
3,c6763c020605467f95f93e8ffbd86e90,Introduction to Data Analysis Using Excel,10166,4.7,NaN,Rice University,NaN,5
4,8fba60d8f2c745ea85cab0a59ccb3575,Linear Regression for Business Statistics,1335,4.8,NaN,Rice University,NaN,5

## COMMENTS:
- About this user, Pooja: She’s a beginner and interested in beginner courses. Topics include Python, basic statistics, and Excel.
- The model is inconsistent with the user's history as suggested courses are mostly for intermediate level. For example, there's no way a beginner would be interested in a course like "Getting started with TensorFlow 2".